import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Integrity of the generated site (run `npm run build` first; `npm run check`
 * does both). Reads the built HTML only: no browser, no network.
 */

const root = fileURLToPath(new URL('..', import.meta.url));
const pagesIn = (dir) =>
  readdirSync(join(root, dir))
    .filter((name) => name.endsWith('.html'))
    .map((name) => join(dir, name));
const pages = [...pagesIn('.'), ...pagesIn('products'), ...pagesIn('brands'), ...pagesIn('pages')];
const read = (page) => readFileSync(join(root, page), 'utf8');
const isRedirect = (html) => html.includes('http-equiv="refresh"') || html.includes('<title>Redirecting');
/** Storefront pages written by the generator (not redirect stubs, not the hand-written design system reference). */
const fullPages = pages.filter((page) => read(page).includes('Generated by scripts/build-html.mjs from src/') && !isRedirect(read(page)));

const attrs = (html, name) => [...html.matchAll(new RegExp(`\\s${name}="([^"]*)"`, 'g'))].map((m) => m[1]);
const local = (url) => url && !/^(https?:|mailto:|tel:|data:|#)/.test(url);
/** File a URL points to. Root-relative URLs (the 404 page, served at any depth) resolve from the site root. */
const target = (page, url) => {
  const path = decodeURI(url.split(/[?#]/)[0]);
  const file = path.startsWith('/') ? join(root, path) : resolve(root, dirname(page), path);
  return path.endsWith('/') ? join(file, 'index.html') : file;
};

test('the site is built', () => {
  assert.ok(fullPages.length >= 50, `only ${fullPages.length} pages found: run npm run build`);
});

test('every internal link, image, script and stylesheet points to a file that exists', () => {
  const missing = [];
  for (const page of pages) {
    const html = read(page);
    const urls = [...attrs(html, 'href'), ...attrs(html, 'src'), ...attrs(html, 'srcset').flatMap((set) => set.split(',').map((part) => part.trim().split(/\s+/)[0]))];
    for (const url of urls.filter(local)) {
      const file = target(page, url);
      if (!existsSync(file) || !statSync(file).isFile()) missing.push(`${page} → ${url}`);
    }
  }
  assert.deepEqual(missing, []);
});

test('no placeholder link or placeholder copy is published', () => {
  for (const page of pages) {
    const html = read(page);
    assert.ok(!/href="#"/.test(html), `${page} has href="#"`);
    assert.ok(!/lorem ipsum/i.test(html), `${page} has lorem ipsum`);
    assert.ok(!/\{\{[^}]+\}\}/.test(html), `${page} has an unfilled {{placeholder}}`);
  }
});

test('every page has a language, a unique title, a description and one h1', () => {
  const titles = new Map();
  for (const page of fullPages) {
    const html = read(page);
    assert.match(html, /<html lang="en/, `${page}: lang`);
    const title = html.match(/<title>([^<]+)<\/title>/)?.[1];
    assert.ok(title, `${page}: title`);
    assert.ok(!titles.has(title), `${page} shares its title with ${titles.get(title)}`);
    titles.set(title, page);
    assert.match(html, /<meta name="description" content="[^"]{20,}"/, `${page}: description`);
    assert.equal((html.match(/<h1[\s>]/g) ?? []).length, 1, `${page}: h1 count`);
  }
});

test('every image has alternative text and declared dimensions', () => {
  for (const page of fullPages) {
    for (const [tag] of read(page).matchAll(/<img\b[^>]*>/g)) {
      assert.match(tag, /\salt="/, `${page}: ${tag.slice(0, 80)}`);
      assert.match(tag, /\swidth="\d+"/, `${page}: width on ${tag.slice(0, 80)}`);
      assert.match(tag, /\sheight="\d+"/, `${page}: height on ${tag.slice(0, 80)}`);
    }
  }
});

test('icon-only buttons and links have an accessible name', () => {
  for (const page of fullPages) {
    for (const [tag, , inner] of read(page).matchAll(/<(button|a)\b[^>]*>([\s\S]*?)<\/\1>/g)) {
      const text = inner.replace(/<svg[\s\S]*?<\/svg>/g, '').replace(/<[^>]+>/g, '').trim();
      const named = text || /aria-label="[^"]+"/.test(tag) || /aria-labelledby=/.test(tag) || /<img[^>]*alt="[^"]+"/.test(inner);
      assert.ok(named, `${page}: unnamed control ${tag.slice(0, 100).replace(/\s+/g, ' ')}`);
    }
  }
});

test('no generated page is orphaned: each one is linked from another page', () => {
  const linked = new Set();
  for (const page of pages) for (const url of attrs(read(page), 'href').filter(local)) linked.add(relative(root, target(page, url)));
  // The home page, and internal pages kept out of search engines (404, design system reference).
  const exempt = (page) => page === 'index.html' || read(page).includes('name="robots" content="noindex"');
  const orphans = fullPages.filter((page) => !linked.has(page) && !exempt(page));
  assert.deepEqual(orphans, []);
});
